##############################
# Command Line Interface
##############################

# Default frontend. Available choices are: zmq, openai, dryrun
# * "dryrun" is a fake frontend that will do nothing other than printing the
#   generated prompt. You can copy it to web-based LLMs in that case.
frontend = 'openai'

##############################
# Specific to OpenAI Frontend
##############################

# OpenAI API is a widely adopted standard. You can switch to other compatible
# service providers, or a self-hosted compatible server.
openai_base_url = "https://api.openai.com/v1"

# API key is necessary to access services including OpenAI's API server.
# https://platform.openai.com/api-keys
openai_api_key = "put-your-api-key-here"

# For instance, gpt-3.5-turbo (4k context; default option), 
# gpt-3.5-turbo-16k (16k context), gpt-4-32k (32k context).
# Their prices vary. See https://platform.openai.com/docs/models .
openai_model = 'gpt-3.5-turbo'

##############################
# Specific to ZMQ Frontend
##############################

# The ZMQ backend URL
zmq_backend = 'tcp://localhost:11177'
